"""Initial schema

Revision ID: cf15da76d787
Revises: 
Create Date: 2026-02-16 13:56:30.381257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf15da76d787'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_table('labor_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department', 'effective_from', name='uq_labor_rate_dept_from')
    )
    op.create_index('ix_labor_rate_dept_from', 'labor_rates', ['department', 'effective_from'], unique=False)
    op.create_table('material_costs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wood_species', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('cost_per_bf', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wood_species', 'grade', 'effective_from', name='uq_material_cost_species_grade_from')
    )
    op.create_index('ix_material_cost_species_grade_from', 'material_costs', ['wood_species', 'grade', 'effective_from'], unique=False)
    op.create_table('overhead_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('overhead_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('waste_factors', sa.JSON(), nullable=False),
    sa.Column('complexity_multipliers', sa.JSON(), nullable=False),
    sa.Column('finishing_costs_per_sqft', sa.JSON(), nullable=False),
    sa.Column('delivery_base_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_per_mile', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('delivery_heavy_surcharge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('installation_multiplier', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('powder_coating_per_sqft', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('max_risk_adjustment_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('planning', 'active', 'completed', 'cancelled', name='project_status'), server_default='planning', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_customer_id', 'projects', ['customer_id'], unique=False)
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'accepted', 'rejected', 'expired', name='quote_status'), server_default='draft', nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('cost_breakdown', sa.JSON(), nullable=False),
    sa.Column('tier_low_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tier_standard_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tier_premium_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('selected_tier', sa.String(length=20), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('risk_flags', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('requires_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['price_book_snapshots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_number')
    )
    op.create_index('ix_quotes_created_at', 'quotes', ['created_at'], unique=False)
    op.create_index('ix_quotes_customer_id', 'quotes', ['customer_id'], unique=False)
    op.create_index('ix_quotes_quote_number', 'quotes', ['quote_number'], unique=False)
    op.create_index('ix_quotes_status', 'quotes', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'estimator', 'viewer', name='user_role'), server_default='estimator', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_log_user_time', 'audit_log', ['user_id', 'created_at'], unique=False)
    op.create_table('completed_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('quoted_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quoted_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_material_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_labor_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_overhead_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_achieved_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('customer_satisfaction', sa.Integer(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('recorded_by_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completed_projects_project_id'), 'completed_projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_completed_projects_quote_id'), 'completed_projects', ['quote_id'], unique=False)
    op.create_table('lost_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('winning_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('competitor', sa.String(length=255), nullable=True),
    sa.Column('loss_reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_quotes_quote_id'), 'lost_quotes', ['quote_id'], unique=False)
    op.create_table('negotiation_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('adjustment_type', sa.String(length=50), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_history_quote_id'), 'negotiation_history', ['quote_id'], unique=False)
    op.create_table('price_book_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_book_snapshots')
    op.drop_index(op.f('ix_negotiation_history_quote_id'), table_name='negotiation_history')
    op.drop_table('negotiation_history')
    op.drop_index(op.f('ix_lost_quotes_quote_id'), table_name='lost_quotes')
    op.drop_table('lost_quotes')
    op.drop_index(op.f('ix_completed_projects_quote_id'), table_name='completed_projects')
    op.drop_index(op.f('ix_completed_projects_project_id'), table_name='completed_projects')
    op.drop_table('completed_projects')
    op.drop_index('ix_audit_log_user_time', table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index('ix_audit_log_created_at', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_quotes_status', table_name='quotes')
    op.drop_index('ix_quotes_quote_number', table_name='quotes')
    op.drop_index('ix_quotes_customer_id', table_name='quotes')
    op.drop_index('ix_quotes_created_at', table_name='quotes')
    op.drop_table('quotes')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_customer_id', table_name='projects')
    op.drop_table('projects')
    op.drop_table('overhead_configs')
    op.drop_index('ix_material_cost_species_grade_from', table_name='material_costs')
    op.drop_table('material_costs')
    op.drop_index('ix_labor_rate_dept_from', table_name='labor_rates')
    op.drop_table('labor_rates')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
